##Multilinear Regression##
### 50_startups
startups<-read.csv('C://Users//lenovo//Desktop//R studio//Data Science Assignments//Multi-Linear Regression//50_Startups.csv')
plot(startups)
model<-lm(Profit~.,data = startups)
summary(model)
library(car)
car::vif(model)
library(MASS)
stepAIC(model)
model2<-lm(Profit~R.D.Spend + Marketing.Spend, data = startups)
summary(model2)
plot(model2)
residualPlots(model2)
avPlots(model2)
qqPlot(model2)
influenceIndexPlot(model2)
startups1<-startups[-c(46,50,15,16),]
model3<-lm(Profit~R.D.Spend + Marketing.Spend, data = startups1)
summary(model3)
plot(model3)
residualPlots(model3)
avPlots(model3)
qqPlot(model3)
influenceIndexPlot(model3)

## Computer_Data##
computer_data<-read.csv('C://Users//lenovo//Desktop//R studio//Data Science Assignments//Multi-Linear Regression//Computer_Data.csv')
plot(computer_data)
model<-lm(price~.,data=computer_data)
summary(model)
library(car)
car::vif(model)
library(MASS)
stepAIC(model)
plot(model)
residualPlots(model)
qqPlot(model)
computer_data['log hd']=log(computer_data$hd)
computer_data2<-computer_data[-c(1441,1701,20,25,26,28,310,308,994,2469),]
model2<-lm(price~.,data = computer_data2)
summary(model2)
plot(model2)
residualPlots(model2)
qqPlot(model2)